//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMultimediaMvc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccesoSeccion
    {
        public int IdAccesoSeccion { get; set; }
        public int IdSeccion { get; set; }
        public short Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public short IdUsuarioCreador { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public short UsuarioModificador { get; set; }
        public bool Acceso { get; set; }
        public bool Crear { get; set; }
        public bool Marcado { get; set; }
        public bool Edicion { get; set; }
        public bool Desactivado { get; set; }
        public short IdRolSistema { get; set; }
    
        public virtual Seccion Seccion { get; set; }
        public virtual RolSistema RolSistema { get; set; }
    }
}
