//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMultimediaMvc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComentarioRespuesta
    {
        public int IdComentarioRespuesta { get; set; }
        public int IdRespuesta { get; set; }
        public short Estado { get; set; }
        public short ScoreObtenido { get; set; }
        public string ComentarioTexto { get; set; }
        public string ComentarioTextoHtml { get; set; }
        public short CantidadEdicion { get; set; }
        public short IdUsuarioCreador { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string NombreUsuarioCreador { get; set; }
        public short IdUsuarioModificador { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string NombreUsuarioModificador { get; set; }
    
        public virtual Respuesta Respuesta { get; set; }
    }
}
