//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMultimediaMvc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogActividad
    {
        public int IdLogActividad { get; set; }
        public short IdRolSistema { get; set; }
        public int IdRolSisCompany { get; set; }
        public string NombreModulo { get; set; }
        public string NombrePagina { get; set; }
        public string Accion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public short IdUsuarioCreador { get; set; }
        public Nullable<int> IdSeccion { get; set; }
        public Nullable<int> IdTema { get; set; }
    
        public virtual Seccion Seccion { get; set; }
        public virtual RolSistema RolSistema { get; set; }
        public virtual RolSistemaCompany RolSistemaCompany { get; set; }
        public virtual Tema Tema { get; set; }
    }
}
