//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMultimediaMvc.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalesERPDBEntities : DbContext
    {
        public SalesERPDBEntities()
            : base("name=SalesERPDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccesoSeccion> AccesoSeccion { get; set; }
        public virtual DbSet<ComentarioRespuesta> ComentarioRespuesta { get; set; }
        public virtual DbSet<ComentarioTema> ComentarioTema { get; set; }
        public virtual DbSet<LogActividad> LogActividad { get; set; }
        public virtual DbSet<Respuesta> Respuesta { get; set; }
        public virtual DbSet<RespuestaContenido> RespuestaContenido { get; set; }
        public virtual DbSet<RolSistema> RolSistema { get; set; }
        public virtual DbSet<RolSistemaCompany> RolSistemaCompany { get; set; }
        public virtual DbSet<Seccion> Seccion { get; set; }
        public virtual DbSet<Tema> Tema { get; set; }
        public virtual DbSet<TemaContenido> TemaContenido { get; set; }
        public virtual DbSet<TemaEdicion> TemaEdicion { get; set; }
        public virtual DbSet<TipoSeccion> TipoSeccion { get; set; }
        public virtual DbSet<TipoTema> TipoTema { get; set; }
        public virtual DbSet<ValoracionRespuesta> ValoracionRespuesta { get; set; }
        public virtual DbSet<ValoracionTema> ValoracionTema { get; set; }
    }
}
