//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMultimediaMvc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespuestaContenido
    {
        public int IdRespuestaContenido { get; set; }
        public int IdRespuesta { get; set; }
        public string Contenido { get; set; }
        public string ContenidHtml { get; set; }
    
        public virtual Respuesta Respuesta { get; set; }
    }
}
