//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMultimediaMvc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Respuesta()
        {
            this.ComentarioRespuesta = new HashSet<ComentarioRespuesta>();
            this.ValoracionRespuesta = new HashSet<ValoracionRespuesta>();
            this.RespuestaContenido = new HashSet<RespuestaContenido>();
        }
    
        public int IdRespuesta { get; set; }
        public int IdTema { get; set; }
        public string Titulo { get; set; }
        public short IdUsuarioCreador { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string NombreUsuarioCreador { get; set; }
        public short IdUsuarioModificador { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string NombreUsuarioModificador { get; set; }
        public byte FlagRespuesta { get; set; }
        public short UsuarioFlagPor { get; set; }
        public System.DateTime FechaFlagPor { get; set; }
        public string NombreFlagPor { get; set; }
        public short Estado { get; set; }
        public short UsuarioEstadoPor { get; set; }
        public System.DateTime FechaEstadoPor { get; set; }
        public string NombreEstadoPor { get; set; }
        public short CantidadVista { get; set; }
        public short ScoreObtenido { get; set; }
        public short CantidadComentario { get; set; }
        public string ResumenEdicion { get; set; }
        public string VisitanteIP { get; set; }
        public short CantidadEdicion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentarioRespuesta> ComentarioRespuesta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValoracionRespuesta> ValoracionRespuesta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RespuestaContenido> RespuestaContenido { get; set; }
        public virtual Tema Tema { get; set; }
    }
}
