//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMultimediaMvc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tema()
        {
            this.ComentarioTema = new HashSet<ComentarioTema>();
            this.LogActividad = new HashSet<LogActividad>();
            this.Respuesta = new HashSet<Respuesta>();
            this.TemaContenido = new HashSet<TemaContenido>();
            this.TemaEdicion = new HashSet<TemaEdicion>();
            this.ValoracionTema = new HashSet<ValoracionTema>();
        }
    
        public int IdTema { get; set; }
        public short IdTipoTema { get; set; }
        public int IdSeccion { get; set; }
        public short Estado { get; set; }
        public string Titulo { get; set; }
        public short CantidadComentario { get; set; }
        public short CantidadRespuesta { get; set; }
        public short ScoreObtenido { get; set; }
        public short CantidadVista { get; set; }
        public string ResumenEdicion { get; set; }
        public short IdUsuarioEstadoPor { get; set; }
        public System.DateTime FechaEstadoPor { get; set; }
        public string NombreEstadoPor { get; set; }
        public byte FlagTema { get; set; }
        public short IdUsuarioFlagPor { get; set; }
        public System.DateTime FechaFlagPor { get; set; }
        public string NombreFlagPor { get; set; }
        public byte IdUsuarioCreador { get; set; }
        public string NombreUsuarioCreador { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public short IdUsuarioModificador { get; set; }
        public string NombreUsuarioModificador { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Tag1 { get; set; }
        public string Tag2 { get; set; }
        public string Tag3 { get; set; }
        public string Tag4 { get; set; }
        public string Tag5 { get; set; }
        public string Tags { get; set; }
        public string VisitanteIP { get; set; }
        public short CantidadEdicion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentarioTema> ComentarioTema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogActividad> LogActividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuesta> Respuesta { get; set; }
        public virtual Seccion Seccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemaContenido> TemaContenido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemaEdicion> TemaEdicion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValoracionTema> ValoracionTema { get; set; }
        public virtual TipoTema TipoTema { get; set; }
    }
}
