//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMultimediaMvc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemaContenido
    {
        public int IdTemaContenido { get; set; }
        public int IdTema { get; set; }
        public string Contenido { get; set; }
        public string ContenidoHtml { get; set; }
    
        public virtual Tema Tema { get; set; }
    }
}
