//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMultimediaMvc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValoracionRespuesta
    {
        public int IdValoracionRespuesta { get; set; }
        public byte Cantidad { get; set; }
        public byte TipoMarca { get; set; }
        public short IdUsuarioCreador { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> IdRespuesta { get; set; }
    
        public virtual Respuesta Respuesta { get; set; }
    }
}
